---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
# Not supported by Serverspec (runuser: command not found)
# - name: centos-5.11
- name: centos-6.6
- name: centos-7.1
- name: debian-6.0.10
- name: debian-7.7
- name: debian-8.1
- name: fedora-20
- name: fedora-21
- name: freebsd-10.0
- name: opensuse-13.1-x86_64
  driver_config:
    box: opscode-opensuse-13.1
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_opensuse-13.1-x86_64_chef-provisionerless.box
- name: ubuntu-10.04
- name: ubuntu-12.04
- name: ubuntu-14.04
- name: ubuntu-14.10
- name: ubuntu-15.04

suites:
- name: default
  run_list:
  - recipe[ramdisk_test::default]
